// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image2":
            case "player":return img`
........................
..................beb...
.................beb....
.....bbb......bbbbbb....
.....b2b.....bbeeeeeb...
.bb..b2bb...bbed1feedf..
bbbb.b22b...bee1ffed4c..
bb4bbb22b...beedfbdd44..
.b44bb22bb..deeeee44444b
.bb44bb222b.beeee44444b.
..bb44bbb22bcbeeee22eb..
....bb44442ecbeee2222...
bbbbbbbb442ceeeeeeeeb...
b2222222eeeeeeeeeeeeb...
bb222b44eeeeeeeeeeeeeb..
.bbbb444eeeeeeeceeeeeb..
...bb4dceeeeeeeceeeeeb..
..bb44bdcdeeeeeceeeeeb..
..bbbbcddccbdecceeeeeb..
......bbbdcccdeeeeeebb..
.......bbccccccceeebb...
........bbbcccccbbbb....
..........bbbbbbb44.....
........................
`;
            case "image1":
            case "turkey":return img`
..............................
..............................
..............................
.....bbb........beb...........
.....b2b.......beb............
.bb..b2bb...bbbbbb............
bbbb.b22b..bbeeeeeb...........
bb4bbb22b.bbed1feedf..........
.b44bb22bbbee1ffed4c..........
.bb44bb22bbeedfbdd44..........
..bb44bbbbdeeeee44444.........
....bb4dddbbeee44444..........
bbbbbbbbdeeeeeee22............
b222222eeeeeeeeeeeb...........
bb222beeeeeebeeeeeb...........
.bbbbbeeeeeebeeeeeb...........
...bbcdceeeedeeeeeb...........
..bb4cbdcdeebeeeeeb...........
..bbbbcddccbdeeeeed...........
.......cbdddddeee44...........
`;
            case "image3":
            case "duck":return img`
. . . . . . . . . . b 5 b . . . 
. . . . . . . . . b 5 b . . . . 
. . . . . . b b b b b b . . . . 
. . . . . b b 5 5 5 5 5 b . . . 
. . . . b b 5 d 1 f 5 d 4 c . . 
. . . . b 5 5 1 f f d d 4 4 4 b 
. . . . b 5 5 d f b 4 4 4 4 b . 
. . . b d 5 5 5 5 4 4 4 4 b . . 
. . b d d 5 5 5 5 5 5 5 5 b . . 
. b d d d d 5 5 5 5 5 5 5 5 b . 
b d d d b b b 5 5 5 5 5 5 5 b . 
c d d b 5 5 d c 5 5 5 5 5 5 b . 
c b b d 5 d c d 5 5 5 5 5 5 b . 
. b 5 5 b c d d 5 5 5 5 5 d b . 
b b c c c d d d d 5 5 5 b b . . 
. . . c c c c c c c c b b . . . 
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
